### PR TITLE
Treat function calls similar to member access when indenting

### PR DESCRIPTION
**Pull request by passabilities**
Before:

```solidity
        SafeERC20
            .safeIncreaseAllowance(IERC20(path[0]), routerAddress, sourceAmount)
            .test
            .test
            .test
            .test
            .test;

        uint256[] memory amounts = IUniswapV2Router(routerAddress)
            .swapExactTokensForTokens(
            sourceAmount,
            minDestination,
            path,
            address(this, aoeu, aoeueu, aoeu)
        );

        uint256[] memory amounts = IUniswapV2Router(routerAddress)
            .swapExactTokensForTokens(
                sourceAmount,
                minDestination,
                path,
                address(this, aoeu, aoeueu, aoeu)
            )
            .test
            .test
            .test
            .test;

        uint256[] memory amounts = IUniswapV2Router(routerAddress)
            .test
            .swapExactTokensForTokens(
                sourceAmount,
                minDestination,
                path,
                address(this, aoeu, aoeueu, aoeu)
            )
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test;

```

After:
```solidity
        SafeERC20.safeIncreaseAllowance(
            IERC20(path[0]),
            routerAddress,
            sourceAmount
        ).test.test.test.test.test;

        uint256[] memory amounts = IUniswapV2Router(routerAddress)
            .swapExactTokensForTokens(
                sourceAmount,
                minDestination,
                path,
                address(this, aoeu, aoeueu, aoeu)
            );

        uint256[] memory amounts = IUniswapV2Router(routerAddress)
            .swapExactTokensForTokens(
                sourceAmount,
                minDestination,
                path,
                address(this, aoeu, aoeueu, aoeu)
            ).test.test.test.test;

        uint256[] memory amounts = IUniswapV2Router(routerAddress)
            .test
            .swapExactTokensForTokens(
                sourceAmount,
                minDestination,
                path,
                address(this, aoeu, aoeueu, aoeu)
            )
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test
            .test;

```

### CODE REVIEW

**Comment by Janther** [comment]
Hey @passabilities 

Could you fix the problems with the current tests not passing?
And make sure you run the linter.

Also add the current format you are solving to the tests so we can be sure we are not destroying anything in the future.

Another thing is please solve one issue per PR. One thing is the indentation and another is grouping the first function call as the first expression of the chain

**Comment by Janther** [comment]
@passabilities I added the tests and fixed the behaviour so the PR doesn't break any of our older tests. I also added this behaviour for `IndexAccess` which is another node that can be at the end of a chain.

If you give me permissions to push commits to your branch, I'll add those and we can proceed with the reviews from the rest of the team.

Otherwise I can make a new PR and will close this one (your commit will still be credited).

**Comment by passabilities** [comment]
@Janther hey sorry for the delay. So since I opened the PR from an organization account, I'm not able to enable changes from maintainers. Only allows that if PR is opened from a user account. I added you to have write access directly tho.

**Comment by Janther** [comment]
Sweet. Tonight I'll push my commits

**Comment by Janther** [comment]
@passabilities I modified your PR to only address the case where the function call is at the end.
The other change where you wanted the function call argument split to have precedence over the split in the chain is inconsistent and we'll need to put more thought into this as there are many cases where this might impact.

**Review by fvictorio — APPROVED** [review]

**Pull request merged**
