### PR TITLE
Adding a test for clean.js so code coverage will shut up about it

### PR DESCRIPTION
**Pull request by Janther**
Does exactly what it says on the tin.

### CODE REVIEW

**Comment by mattiaerre** [comment]
this shouldn't be necessary if you run the tests w/ `AST_COMPARE=true npm test`
could you please have a look and confirm?

**Comment by Janther** [comment]
can we configure the Codecov Report using `AST_COMPARE=true` then?
Every PR that I make has a red square in the corner 😂 
Screenshot 2019-06-11 22 45 13

**Comment by fvictorio** [comment]
Alternatively, just ignore that file in the coverage?

**Comment by mattiaerre** [comment]
let me have a look into this

**Comment by mattiaerre** [comment]
shall we close this one because of #151 ?

**Comment by Janther** [comment]
happily

**Pull request closed without merging**
