### PR TITLE
Don't indent the leftmost operand

### PR DESCRIPTION
**Pull request by jablko**
Like [language-js](https://github.com/prettier/prettier/blob/master/src/language-js/printer-estree.js#L645).

### CODE REVIEW

**Comment by Janther** [comment]
Hi @jablko, could you add the scenario in the tests please?

**Comment by Janther** [comment]
also as far as I understand the leftmost operand is already not being indented so if I could see an example of this case not being applied.

**Comment by jablko** [comment]
> Hi @jablko, could you add the scenario in the tests please?

Definitely: I've now added tests. It avoids formatting
```Solidity
veryVeryVeryVeryVeryLongFunctionCalledA(
    veryVeryVeryVeryVeryLongVariableCalledB
 ) +
    c;
```
as
```Solidity
veryVeryVeryVeryVeryLongFunctionCalledA(
        veryVeryVeryVeryVeryLongVariableCalledB
    ) +
    c;
```

**Comment by Janther** [comment]
@jablko, could you please include this change in `src/binary-operator-printers/exponentiation.js` which was created in #174

**Comment by jablko** [comment]
> could you please include this change in `src/binary-operator-printers/exponentiation.js` which was created in #174

Sure thing: Done.

**Pull request merged**
