### PR TITLE
4 spaces indentation

### PR DESCRIPTION
**Pull request by Janther**
Solidity industry indents using 4 spaces and this opinionated code formatter should follow the industry.

### CODE REVIEW

**Comment by mattiaerre** [comment]
I've got no particular preference but I see there are some strange indentations in the snapshots?

**Comment by Janther** [comment]
everything that is code related has 4 spaces indentation (I changed these manually before running the tests).
However, block comments look a bit weird. I added a TODO [line](https://github.com/prettier-solidity/prettier-plugin-solidity/pull/122/files#diff-1fdf421c05c1140f6d71444ea2b27638R60)

Also, snapshots contain the code before and after the format so you might also be looking at the code before the format, which contains different types of indentation (2 spaces, 4 spaces, tabs, etc) and trailing whitespace.

**Comment by fvictorio** [comment]
LGTM. @Janther, can you give an example of some block comment that looks weird after being formatted?

**Comment by Janther** [comment]
For example, this is the block before formatting:

https://github.com/prettier-solidity/prettier-plugin-solidity/blob/f80a9a811b53c95e8a40ecb81e5606ea7abb3b7f/tests/BasicIterator/__snapshots__/jsfmt.spec.js.snap#L36-L38

and after formatting it looks like this:

https://github.com/prettier-solidity/prettier-plugin-solidity/blob/f80a9a811b53c95e8a40ecb81e5606ea7abb3b7f/tests/BasicIterator/__snapshots__/jsfmt.spec.js.snap#L80-L82

also tabs are kept within these blocks

https://github.com/prettier-solidity/prettier-plugin-solidity/blob/f80a9a811b53c95e8a40ecb81e5606ea7abb3b7f/tests/BasicIterator/__snapshots__/jsfmt.spec.js.snap#L49-L51

**Comment by Janther** [comment]
trying these out with prettier on javascript, it has the same issue.
I think the Prettier team doesn't mind.

**Comment by fvictorio** [comment]
Yeah, the formatting of comments is handled by prettier itself. If the same thing happens in js, I think we can ignore it here.

Keeping the tabs seems OK to me: it makes sense to keep the comment's content verbatim.

The first example does look wrong though. Maybe you can open an issue in Prettier's repo?

**Comment by mattiaerre** [comment]
if we are all happy I'll merge and deploy

**Pull request merged**
