### PR TITLE
Return statements are already indented

### PR DESCRIPTION
**Pull request by jablko**
### Before

```Solidity
return
    keccak(self, offset, self.length - offset) ==
        keccak(other, otherOffset, other.length - otherOffset);
```

### After

```Solidity
return
    keccak(self, offset, self.length - offset) ==
    keccak(other, otherOffset, other.length - otherOffset);
```

### CODE REVIEW

**Comment by mattiaerre** [comment]
same comment as https://github.com/prettier-solidity/prettier-plugin-solidity/pull/190#issuecomment-519379159

**Comment by jablko** [comment]
### Before

```Solidity
return
    keccak(self, offset, self.length - offset) ==
        keccak(other, otherOffset, other.length - otherOffset);
```

### After

```Solidity
return
    keccak(self, offset, self.length - offset) ==
    keccak(other, otherOffset, other.length - otherOffset);
```

**Comment by mattiaerre** [comment]
some conflicts that need to be resolved @jablko thanks

**Comment by mattiaerre** [comment]
thanks so much, @jablko, I will merge and release a new version of the plugin

**Comment by jablko** [comment]
@mattiaerre Thank you!

**Pull request merged**
