### PR TITLE
Adjust stateMutability in function modifier order

### PR DESCRIPTION
**Pull request by benkostr**
Not sure if you want this, but it would follow the Solidity style guide.
https://solidity.readthedocs.io/en/v0.7.2/style-guide.html#function-declaration

Specifically:
The modifier order for a function should be:

1. Visibility
2. Mutability
3. Virtual
4. Override
5. Custom modifiers

### CODE REVIEW

**Comment by fvictorio** [comment]
I'm personally ok with this. But I'm surprised that tests passed, this means that we need more tests for the modifiers order. Would you mind adding some? We don't need to try all possible orders, that would be crazy, but just a few.

**Comment by fvictorio** [comment]
For the record: OpenZeppelin seems to use this order

**Comment by mattiaerre** [comment]
thanks for this PR @benkostr 🙏 
are we ok w/ this drop in coverage @fvictorio ?
it seems weird to me too that "just" flipping a line has that impact

**Review by fvictorio — APPROVED** [review]

**Comment by fvictorio** [comment]
Yeah, I'm pretty sure it's a false negative.

**Pull request merged**
