### PR TITLE
Fix prettier removing payable from address payable

### PR DESCRIPTION
**Pull request by svechinsky**
So I noticed an issue with the new address payable type.
At first the plugin would fail because the published version of solidity-parser-antlr had a bug and didn't recognize the payable keyword.
After using the most recent version from git I noticed that the printer would just remove the payable keyword.

So this PR fixes this.
I have absolutley no idea if what I did here is the correct way to fix it but it seems to work for me.
Also I have no idea what's the best way to include the most recent version of solidity-parser-antlr, maybe best to ask the maintainer to publish the newest version?

### CODE REVIEW

**Comment by svechinsky** [comment]
Fixed some styling issues, also https://github.com/federicobond/solidity-parser-antlr/issues/40 the new version was released so this should be mergable

**Comment by fvictorio** [comment]
@svechinsky could you add tests for this?

**Comment by mattiaerre** [comment]
thanks for this PR @svechinsky if you can add a test that would be really appreciated if you cannot please comment w/ an example from a contract where you've noticed the issue and we'll add the test for you as we'd like to make sure that the fix doesn't introduce regression as well as improve the overall code coverage

**Comment by svechinsky** [comment]
I won't be able to write the test myself but will post an example later
today.

**Comment by mattiaerre** [comment]
thanks @svechinsky

**Comment by svechinsky** [comment]
So if you run prettier on this function the payable part will be removed (both in the parameters as well as in the declaration).
```solidity
contract AddressPayable{
 function sendSomeEth(address payable to){
   address payable target = to;
   target.transfer(100 eth);
}
}
```

**Comment by mattiaerre** [comment]
hi @svechinsky can you grant me write access to your fork so that I can push the test? otherwise you can add the attached folder to the project under `tests`

[AddressPayable.zip](https://github.com/prettier-solidity/prettier-plugin-solidity/files/2715776/AddressPayable.zip)

**Comment by fvictorio** [comment]
Added the tests. @mattiaerre, just FYI, you can push to a forked repo when there's a pull request like this :slightly_smiling_face:

**Comment by fvictorio** [comment]
This closes #78, right?

**Pull request merged**
