### PR TITLE
fixing array indentation and also solved the return statements.

### PR DESCRIPTION
**Pull request by Janther**
Solving #145, by chance this also solves #140 (sorry @minggas).

However this uncovered 2 hidden bugs.

1. Trailing comments are considered in the `printWidth` rule.
2. `if` and `while` and `for` conditions should break in the logic operators. `||`, `&&`, `<`, `>`,`<=`, `>=`, `==`

### CODE REVIEW

**Comment by fvictorio** [comment]
I don't get why a change in `TupleExpression` affects condition expressions inside `if`s :confused:

**Comment by Janther** [comment]
is not the `if` condition that gets broken, is the `TupleExpression` within the `if`

```Solidity
// This is ok but not great
if (veryLongConditionWontBreak) {}

// It should look like this
if (
    veryLongConditionShouldBreak
) {}

// This looks weird
if ((
    4 + 5
) / 6 < thisIsAVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongName) {
}

// It should look like this
if (
    (4 + 5) / 6 <
    thisIsAVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongName
) {
}
```
But this is a bug that will be solved as we define better grouping within each node.

**Comment by fvictorio** [comment]
Oh, I see. Weird that those kind of expressions are called `TupleExpressions`.

**Comment by Janther** [comment]
I believe Tuple refers to the pair of parentheses `()` or `[]`, so these apply to arrays, returns and parentheses in any computation.

**Pull request merged**
