### PR TITLE
Avoid TypeError:

### PR DESCRIPTION
**Pull request by jablko**
Cannot read property 'range' of null

### CODE REVIEW

**Comment by mattiaerre** [comment]
thanks for this PR @jablko do you think you are able to add a test that covers this branch?

**Comment by jablko** [comment]
> thanks for this PR @jablko do you think you are able to add a test that covers this branch?

Done: I've now added an input that triggers this error.

**Comment by fvictorio** [comment]
Unrelated to this PR, but maybe we should format empty fors as `for (;;)`?

**Comment by mattiaerre** [comment]
that's a good point @fvictorio , what do you think we should be doing? shall I wait to merge this PR?

 // cc @jablko @Janther

**Comment by fvictorio** [comment]
I'll just open an issue, I think we can merge this.

**Comment by Janther** [comment]
:thumbsup:

**Comment by yxliang01** [comment]
I'm thinking whether this PR will create silent errors. I feel like prettier-plugin-solidity is in fact expecting `node.expression` is defined at the time that if-condition is being executed. As prettier-plugin-solidity has been working okay, I suspect that only when the AST is somehow unexpected will cause `TypeError` in this case (e.g. breaking changes of `solidity-parser-antlr`). As such, maybe an `assert` statement would be more appropriate?

**Comment by mattiaerre** [comment]
thanks for this feedback @yxliang01 ; what do you think about this @Janther @fvictorio ?
// cc @jablko

**Pull request merged**
