### PR TITLE
del-6-add-12

### LINKED ISSUE #184: kill node 6 support
# Description

Node.js 6 is no longer maintained so I think we should kill it an maybe add support for Node.js 12 https://nodejs.org/en/about/releases/

### PR DESCRIPTION
**Pull request by mattiaerre**
# Description

- goodbye node 6 welcome node 12

closes #184

### CODE REVIEW

**Comment by Janther** [comment]
also maybe to celebrate this event, lets also update the dependencies:

| Package              | Current | Wanted | Latest |
| -------------------- | ------- | ------ | ------ |
| escape-string-regexp | 1.0.5   | 1.0.5  | 2.0.0  |
| eslint               | 5.16.0  | 5.16.0 | 6.1.0  |
| string-width         | 3.1.0   | 3.1.0  | 4.1.0  |

**Comment by mattiaerre** [comment]
very good idea @Janther I'm going to update all the things 😅

**Comment by mattiaerre** [comment]
@fvictorio it looks like Travis is failing because:

`The command "npm ls" exited with 1.`

can we remove it?

**Comment by mattiaerre** [comment]
waiting for @fvictorio to confirm, no rush 😉

**Pull request merged**
