### PR TITLE
Modifiers now will keep virtual and override

### LINKED ISSUE #279: Support `virtual` and `override` for modifiers.
Currently it works for functions, but not for modifiers.

Example:

```solidity
modifier onlyOwner() virtual;

modifier onlyOwner() override {
    require(msg.sender == owner(), "Ownable: caller is not the owner");
    _;
}
```

### PR DESCRIPTION
**Pull request by Janther**
fixes #279 and #277 
bumping the dependency and also tweaking the variable declaration node.

### CODE REVIEW

**Comment by mattiaerre** [comment]
I think I can merge #286 first @Janther what do you think?

**Comment by Janther** [comment]
I also updated the parser before dependabot did, so I’m not sure what type
of conflicts will be there.
It’s up to you.

**Comment by mattiaerre** [comment]
it looks like it did it before you did it and also I thought you were happy about that since you suggested to use dependabot. in this case, I'll close its PR and merge yours instead.

**Comment by Janther** [comment]
Well yes but in my local machine I already had the changes

**Comment by fvictorio** [comment]
Thanks for doing this @Janther!

**Pull request merged**
