### PR TITLE
update-deps

### PR DESCRIPTION
**Pull request by mattiaerre**
# Description

- update dependencies

### CODE REVIEW

**Comment by Janther** [comment]
I downgraded the versions of these packages to support `node 6`

| Package                | Current | Wanted | Latest |
| ---------------------- | ------- | ------ | ------ |
| `escape-string-regexp` | 1.0.5   | 1.0.5  | 2.0.0  |
| `eslint`               | 5.16.0  | 5.16.0 | 6.0.1  |
| `string-width`         | 3.1.0   | 3.1.0  | 4.1.0  |

If we want to upgrade these we will have to stop supporting `node 6` in our travis config.

**Comment by mattiaerre** [comment]
@Janther yes I've noticed that that was the problem, I'm down to stop supporting node 6 tbh, what do you think?

**Comment by Janther** [comment]
It’s very tricky to decide which versions to use. In my own projects I tend
to use always the latest versions of packages but in an open source one we
might want to keep using older ones as long as we don’t find a critical
issue.
Anyway at the moment we don’t have much info on how much this tool is
being used and in which scenarios.
I recon it’s used in new versions of node only.
I would add an `engines` attribute in our `package.json` if we are not
gonna support a node version.

**Comment by mattiaerre** [comment]
Yeah, I agree. let's do this 👍

**Pull request merged**
